### ISSUE TITLE
flarectl dns list: TXT records are incorrectly split on whitespace

### ISSUE THREAD

**Issue by ghost** [cloudflare/cloudflare-go#170] opened 2018-03-06 16:26 UTC
```
$ ./flarectl.linux.amd64 dns list --zone test.domain
                 ID                | TYPE  |             NAME              |               CONTENT                | PROXIED | TTL
+----------------------------------+-------+-------------------------------+--------------------------------------+---------+-----+
  xxxxyyyyzzzzxxxxyyyyzzzzxxxxyyyy | A     | test.domain                   | x.x.y.y                              | false   |   1
  xxxxyyyyzzzzxxxxyyyyzzzzxxxxyyyy | A     | gateway.test.domain           | x.x.y.y                              | false   |   1
  xxxxyyyyzzzzxxxxyyyyzzzzxxxxyyyy | A     | mail.test.domain              | x.x.y.y                              | false   |   1
  xxxxyyyyzzzzxxxxyyyyzzzzxxxxyyyy | A     | mail.test.domain              | x.x.y.y                              | false   |   1
  xxxxyyyyzzzzxxxxyyyyzzzzxxxxyyyy | AAAA  | test.domain                   | x:x:x:x:y:y:y:y                      | false   |   1
  xxxxyyyyzzzzxxxxyyyyzzzzxxxxyyyy | CNAME | fm1._domainkey.test.domain    | fm1.test.domain.dkim.fmhosted.com    | false   |   1
  xxxxyyyyzzzzxxxxyyyyzzzzxxxxyyyy | CNAME | fm2._domainkey.test.domain    | fm2.test.domain.dkim.fmhosted.com    | false   |   1
  xxxxyyyyzzzzxxxxyyyyzzzzxxxxyyyy | CNAME | fm3._domainkey.test.domain    | fm3.test.domain.dkim.fmhosted.com    | false   |   1
  xxxxyyyyzzzzxxxxyyyyzzzzxxxxyyyy | CNAME | mesmtp._domainkey.test.domain | mesmtp.test.domain.dkim.fmhosted.com | false   |   1
  xxxxyyyyzzzzxxxxyyyyzzzzxxxxyyyy | CNAME | vpn.test.domain               | gateway.test.domain                  | false   |   1
  xxxxyyyyzzzzxxxxyyyyzzzzxxxxyyyy | MX    | test.domain                   | 10 in1-smtp.messagingengine.com      | false   |   1
  xxxxyyyyzzzzxxxxyyyyzzzzxxxxyyyy | MX    | test.domain                   | 20 in2-smtp.messagingengine.com      | false   |   1
  xxxxyyyyzzzzxxxxyyyyzzzzxxxxyyyy | SRV   | _caldavs._tcp.test.domain     | 0 1 443 caldav.fastmail.com          | false   |   1
  xxxxyyyyzzzzxxxxyyyyzzzzxxxxyyyy | SRV   | _carddavs._tcp.test.domain    | 0 1 443 carddav.fastmail.com         | false   |   1
  xxxxyyyyzzzzxxxxyyyyzzzzxxxxyyyy | SRV   | _imaps._tcp.test.domain       | 0 1 993 imap.fastmail.com            | false   |   1
  xxxxyyyyzzzzxxxxyyyyzzzzxxxxyyyy | SRV   | _pop3s._tcp.test.domain       | 10 1 995 pop.fastmail.com            | false   |   1
  xxxxyyyyzzzzxxxxyyyyzzzzxxxxyyyy | SRV   | _submission._tcp.test.domain  | 0 1 587 smtp.fastmail.com            | false   |   1
  xxxxyyyyzzzzxxxxyyyyzzzzxxxxyyyy | TXT   | test.domain                   | v=spf1                               | false   |   1
                                   |       |                               | include:spf.messagingengine.com      |         |
                                   |       |                               | ~all                                 |         |
```

Note the TXT record at the end. It's being separated at whitespace into three output records rather than being displayed as a single TXT record.

**Comment by sushsada** [comment] 2020-04-21 03:04
This seems to be work for me with the latest:
```
➜  cloudflare-go git:(master) go run    github.com/cloudflare/cloudflare-go/cmd/flarectl --version               
flarectl version 2017.10.0
➜  cloudflare-go git:(master) go run    github.com/cloudflare/cloudflare-go/cmd/flarectl dns list --zone test.example
                 ID                | TYPE  |       NAME       |           CONTENT            | PROXIED | TTL  
-----------------------------------+-------+------------------+------------------------------+---------+------
  abcdefgbijajklsdfkjhasdkjfhalkjs | A     | test.example     | 1.2.3.4                      | false   |   1  
  abcdefgbijajklsdfkjhasdkjfhalkjs | CNAME | www.test.example | test.example                 | false   |   1  
  abcdefgbijajklsdfkjhasdkjfhalkjs | TXT   | test.example     | text separated by whitespace | false   |   1  
➜  cloudflare-go git:(master) 
```
Note that I anonymized the id and the domain names.

**Comment by patryk** [comment] 2020-10-07 13:12
Thanks @sushlala for verification. Closing.

**Closed by patryk** 2020-10-07 13:12 UTC

**Comment by elimn** [comment] 2021-04-26 20:57
Just FYI I can reproduce this issue with a long SPF record, same as you @ghost. But, I don't believe it's a bug. I get the same thing with any record that exceeds 30 characters in length, and it's just how the tabled output displays such long records. By wrapping them to a new line.
