### ISSUE TITLE
CertificateAuthority field is omitempty on CustomHostnameSSL

### ISSUE THREAD

**Issue by jameshartig** [cloudflare/cloudflare-go#3029] opened 2024-09-06 05:28 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

v0.103.0

### Go environment

N/A

### Expected output

Cloudflare recommends that you set the `certificate_authority` field to `""` before September 9, 2024 [1]. I expect to be able to set that field to an empty string.

[1] https://developers.cloudflare.com/ssl/reference/migration-guides/lets-encrypt-chain/#custom-hostname

### Actual output

Currently the Go API would omit that field from the PATCH call if it's set to an empty string.

### Code demonstrating the issue
```go
package main

import (
	"context"

	"github.com/cloudflare/cloudflare-go"
)

var zoneID = ""
var token = ""

func main() {
	ctx := context.Background()
	cf, err := cloudflare.NewWithAPIToken(token)
	if err != nil {
		panic(err)
	}

	page := 1
	for {
		hostnames, info, err := cf.CustomHostnames(ctx, zoneID, page, cloudflare.CustomHostname{})
		if err != nil {
			panic(err)
		}
		for _, h := range hostnames {
			if h.SSL.CertificateAuthority != "" {
				updated := cloudflare.CustomHostname{
					SSL: h.SSL,
				}
				updated.SSL.CertificateAuthority = ""
				resp, err := cf.UpdateCustomHostname(ctx, zoneID, h.ID, updated)
				if err != nil {
					panic(err)
				}
				if resp.Result.SSL.CertificateAuthority != "" {
					panic("failed to update CertificateAuthority")
				}
			}
		}
		if info.Done() {
			break
		}
		page++
	}
}
```

### Steps to reproduce

See above code

**Comment by jacobbednarz** [comment] 2024-09-09 05:02
this is by design as the schemas do not define an empty string as an allowed value and that is what is used as the source of truth for these SDKs. when/if the internal teams update the schemas, they can also update the library here to account for the empty string handling. going to close this off as a feature request that the internal teams can consider and for now, i'd recommend updating the value to be the expected CA instead.

**Closed as not planned by jacobbednarz** 2024-09-09 05:02 UTC
Labels: needs-triage
