### ISSUE TITLE
API Missmatch between GetTunnelConfiguration between Json and GoLangStructs

### ISSUE THREAD

**Issue by SimonStiil** [cloudflare/cloudflare-go#1273] opened 2023-04-24 20:25 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

v0.65.0

### Go environment

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/simon/.cache/go-build"
GOENV="/home/simon/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/simon/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/simon/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/simon/workspace/go/cloudflaretunnel/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3338449984=/tmp/go-build -gno-record-gcc-switches"

### Expected output

Do Curl Example from https://developers.cloudflare.com/api/operations/cloudflare-tunnel-configuration-get-configuration
With a OriginRequestConfig
format is 
  "result": {
    "tunnel_id": "[ID]",
    "version": 11,
    "config": {
      "ingress": [
        {
          "service": "https://192.168.1.20",
          "hostname": "tunnel-test.example.com",
          "originRequest": {
            "originServerName": "tunnel-test.example.com"
          }
        },
        {
          "service": "http_status:404"
        }
      ],
      "warp-routing": {
        "enabled": true
      }
    },
    "source": "cloudflare",
    "created_at": "2023-04-24T19:47:25.269489Z"
  }

### Actual output

https://pkg.go.dev/github.com/cloudflare/cloudflare-go#TunnelConfiguration
Format of goLang Structs:
type TunnelConfiguration struct {
	Ingress       [][UnvalidatedIngressRule](https://pkg.go.dev/github.com/cloudflare/cloudflare-go#UnvalidatedIngressRule) `json:"ingress,omitempty"`
	WarpRouting   *[WarpRoutingConfig](https://pkg.go.dev/github.com/cloudflare/cloudflare-go#WarpRoutingConfig)       `json:"warp-routing,omitempty"`
	OriginRequest [OriginRequestConfig](https://pkg.go.dev/github.com/cloudflare/cloudflare-go#OriginRequestConfig)      `json:"originRequest,omitempty"`
}
OriginRequestConfig is not part of UnvalidatedIngressRule but beside ingress. Not following reply from API server.

Trying to work with OriginRequestConfig results in 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6675c4]

### Code demonstrating the issue

tunnelConfiguration, err := api.GetTunnelConfiguration(context.Background(), accountIdentifier, tunnelID)
fmt.Printf("Configuration %s %d (%s):\n", tunnelConfiguration.TunnelID, tunnelConfiguration.Version, *tunnelConfiguration.Config.OriginRequest.HTTPHostHeader)

### Steps to reproduce

Create Tunnel
Create Public Hostname (set HTTP Setting > HTTP Host Header)
Try code from above.

Would prefer Go Structs follow web API as OriginRequestConfig seems to make the most sense following the IngressRule
Issue also the same for UpdateTunnelConfiguration as it follows same spec.

**Comment by jacobbednarz** [comment] 2023-04-24 21:13
duplicate of #1098

**Closed as not planned** 2023-04-24 21:13 UTC
