### ISSUE TITLE
flarectl zone list only shows the first 20 zones

### ISSUE THREAD

**Issue by matthewlenz** [cloudflare/cloudflare-go#214] opened 2018-08-06 02:48 UTC
When using flarectl to list my zones only the first 20 zones are listed.

**Comment by wordskill** [comment] 2018-08-13 14:17
I have experienced the same problem.

**Comment by garrettgalow** [comment] 2018-08-13 21:35
I believe this clearly points out why that is: https://github.com/cloudflare/cloudflare-go/blob/master/zone.go#L320 our default paging is 20

**Comment by wordskill** [comment] 2018-08-14 03:40
@garrettgalow Thanks for pointing out that unfortunate limitation.

**Comment by rvalitov** [comment] 2018-09-17 07:13
The PR is waiting there for half a year to be merged, but it seems that CloudFlare is not interested in maintaining this project.

**Comment by pmocek** [comment] 2018-10-17 17:57
> our default paging is 20

The line referenced indicates that pagination is still on the to-do list and that currently instead of paging, we show only the first page of results.

**Comment by pmocek** [comment] 2018-10-17 17:59
This seems not to be a description of a bug, but of user error, as the aforementioned comment suggests that showing only a subset of zones is the designed behavior.

**Comment by pmocek** [comment] 2018-10-17 18:00
related: #182

**Comment by wordskill** [comment] 2018-10-17 18:09
It is a bug because the API is intended to be a first-class channel to interact with your account. A consequence of this limitation, most likely unintended, is that users with more than 20 domains (precisely the users you would expect to benefit most from an API) must revert to using the website.

You can actually see the same limitation breaking website functionality when you try to submit a support ticket: the form asks you to select the specific domain that is encountering a problem, but the form will only list your first 20 domains.

**Comment by pmocek** [comment] 2018-10-17 20:09
> the API is intended to be a first-class channel to interact with your account

This is not the API.  It is software that uses the API: flarectl.  And this software is, as evidenced by the aforementioned source code comment, explicitly intended to show only the first page of results in this situation.  As flarectl does not override the [default page size of 20](https://api.cloudflare.com/#zone-list-zones), a maximum of 20 results are returned in response to the API call, and a maximum of 20 are printed by flarectl.

Unfortunate design?  Sure.  Fails to meet many users' needs?  Almost certainly.  But it is working as intended.

Solution is a change in functionality not a fix for unintended behavior; implementation of a feature request rather than fixing of a bug.

> when you try to submit a support ticket: the form asks you to select the specific domain that is encountering a problem, but the form will only list your first 20 domains.

￼￼That is the result of yet another program that uses the API.  In that case, it is Cloudflare's web UI.

**Comment by rvalitov** [comment] 2019-05-13 22:57
ping

**Comment by jacobbednarz** [comment] 2019-05-13 23:01
@rvalitov What part of this isn't working for you? `ListZones` has paginated since #288 landed in May. If you're still experiencing issues, you should probably open a new issue as the issue mentioned here is no longer relevant.

**Comment by rvalitov** [comment] 2019-08-27 06:41
@jacobbednarz Thank you, everything works! The only thing that's confusing is that the flarectl version always reports the same version "2017.10.0", so it seemed to me it wasn't updated. Anyway, this issue is solved.

**Comment by jacobbednarz** [comment] 2019-08-27 08:24
Heh, it sure does https://github.com/cloudflare/cloudflare-go/blob/master/cmd/flarectl/flarectl.go#L16

That seems like a bug to report. Potentially looking to align the Go library version and the CLI would be ideal.

**Comment by rvalitov** [comment] 2019-08-27 08:51
Posted a new [issue ](https://github.com/cloudflare/cloudflare-go/issues/343)

**Comment by patryk** [comment] 2019-12-12 14:03
Fixed by https://github.com/cloudflare/cloudflare-go/pull/288

**Closed by patryk** 2019-12-12 14:03 UTC
