### ISSUE TITLE
ListSSL time unmarshalling error

### ISSUE THREAD

**Issue by vanbroup** [cloudflare/cloudflare-go#164] opened 2018-02-23 14:32 UTC
When using the ListSSL function for custom certificates an error is returned:

```
unmarshalling the JSON response: parsing time ""2017-02-07 13:06:07.962222+00"" as ""2006-01-02T15:04:05Z07:00"": cannot parse " 13:06:07.962222+00"" as "T"
```

**Comment by inge4pres** [comment] 2018-12-21 12:57
Facing this very same error right now: the problem is that  [TestListSSL](https://github.com/cloudflare/cloudflare-go/blob/master/ssl_test.go#L82) nor the [API documentation](https://api.cloudflare.com/#custom-ssl-for-a-zone-list-ssl-configurations) are updated with regards to what the API actually returns.

If running a cURL on the API, this is the response
```
{
  "result": [
    {
      "id": "bea93a4d9ca08e5cb7cb7488b2c083a5",
      "type": "legacy_custom",
      "hosts": [
           "example.org"
       ],
"issuer": "REDACTED",
      "signature": "SHA256WithRSA",
      "bundle_method": "ubiquitous",
      "zone_id": "REDACTED",
      "uploaded_on": "2018-09-24 11:41:36.697534+00",
      "modified_on": "2018-09-24 11:41:36.697534+00",
      "expires_on": "2019-09-10 23:59:59+00",
      "priority": 20,
      "status": "active"
    }
  ],
  "result_info": {
    "page": 1,
    "per_page": 20,
    "total_pages": 1,
    "count": 1,
    "total_count": 1
  },
  "success": true,
  "errors": [],
  "messages": []
}
```

Here we have a different time format than what expressed in the tests.
Problem also verifies without any certificates installed in the zone as it seems there is a time set with `Now()` somewhere so also trying to list an empty configuration fails.
to patch this all the tests involving this API should be rewritten with the actual value returned by the API, or the API code changed.
For the the first path, I can help rebuilding the tests and using the proper time format, so the parsing part should be corrected from `time.Parse(time.RFC3339, timeFromAPI)` with `time.Parse("2006-01-02 15:04:05.000000+07", timeFromAPI).

**Comment by inge4pres** [comment] 2018-12-21 13:02
And `expires_on` format parsing would be `time.Parse("2006-01-02 15:04:05+07", timeFromAPI)`

**Comment by jacobbednarz** [comment] 2018-12-23 22:03
@patryk Do you mind confirming which timestamp format is expected here?

**Comment by inge4pres** [comment] 2019-02-04 10:33
Any news on this?

**Comment by inge4pres** [comment] 2019-08-05 11:59
I think this was resolved by the API change on May 8th that was communicated by Brian Carbone @ Cloudflare... anyone able to test if this is the case?

**Comment by jacobbednarz** [comment] 2019-08-20 00:17
This looks sorted from my end. Leaving this closed unless we find an issue with it.

**Comment by patryk** [comment] 2019-12-12 13:59
Fixed by https://github.com/cloudflare/cloudflare-go/pull/387

**Closed by patryk** 2019-12-12 13:59 UTC
