### ISSUE TITLE
cloudflare.OriginRequestConfig Duration is incorrect unit

### ISSUE THREAD

**Issue by kamontat** [cloudflare/cloudflare-go#1257] opened 2023-04-03 15:57 UTC
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

v0.63.0

### Go environment

```env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="<hidden>/Library/Caches/go-build"
GOENV="<hidden>/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="<hidden>/.asdf/installs/golang/1.20.1/packages/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="<hidden>/.asdf/installs/golang/1.20.1/packages"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="<hidden>/.asdf/installs/golang/1.20.1/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="<hidden>/.asdf/installs/golang/1.20.1/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="<hidden>/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8w/3sgs6h1s55773snm6gqgw8780000gn/T/go-build1902134300=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### Expected output

Able to connect to origin request with configuration

### Actual output

Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp <ip>:443: i/o timeout

### Code demonstrating the issue

```golang
func get[T any](i T) *T {
	return &i
}
var config = cloudflare.OriginRequestConfig{
		ConnectTimeout:       get(15 * time.Second),
		TLSTimeout:           get(15 * time.Second),
		TCPKeepAlive:         get(15 * time.Second),
		KeepAliveConnections: get(50),
		KeepAliveTimeout:     get(2 * time.Minute),
}

var params = TunnelConfigurationParams{
  TunnelID: config.Record.Id,
  Config: TunnelConfiguration{
    Ingress:       ingresses,
    OriginRequest: config,
  },
}
````

### Steps to reproduce

All `cloudflare.OriginRequestConfig` duration should be parsed to second unit before sent to APIs.
Otherwise it will got something like below
```json
{"originRequest": {
  "connectTimeout":15000000000,
  "keepAliveTimeout":120000000000,
  "keepAliveConnections":50,
  "tlsTimeout":15000000000,
  "tcpKeepAlive":15000000000
}}
```

**Comment by jacobbednarz** [comment] 2023-04-04 00:24
duplicate of #1096

**Closed as not planned by jacobbednarz** 2023-04-04 00:24 UTC
